version: '3.8'

services:
  db:
    image: postgres:15
    container_name: repsy-postgres
    environment:
      POSTGRES_DB: rep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: repsy-app
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rep
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      STORAGESTRATEGY: file-system
    volumes:
      - ./storage:/app/storage

volumes:
  postgres_data: